# Generated by Django 2.2.4 on 2019-12-07 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalAddress',
            fields=[
                ('HospitalAddress_ID', models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False)),
                ('Home', models.CharField(max_length=250)),
                ('Street', models.CharField(max_length=250)),
                ('Pin', models.CharField(default=0, max_length=6)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.Area')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.City')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Company_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Company_Name', models.CharField(max_length=200)),
                ('Company_Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region=None)),
                ('Company_Email', models.EmailField(default='asd@rew.com', max_length=254)),
                ('Company_License_Number', models.CharField(default='1234567890', max_length=25, null=True)),
                ('Company_Logo', models.ImageField(default='default-user-image.jpg', null=True, upload_to='media')),
                ('Company_Activate', models.BooleanField(default=False)),
                ('Company_Address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Corporate.HospitalAddress')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
