# Generated by Django 2.2.7 on 2019-12-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Corporate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaladdress',
            name='HospitalAddress_ID',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
