# Generated by Django 2.2.7 on 2019-12-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='username',
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='abc', max_length=254),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(default='abc', max_length=1000),
        ),
    ]
