# Generated by Django 2.2.7 on 2019-12-12 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeDonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Donor', models.CharField(max_length=50)),
                ('time_of_death', models.TimeField()),
                ('attendee_name', models.CharField(max_length=50)),
                ('contact_info', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region=None)),
                ('City', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrganDonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Donor', models.CharField(max_length=50)),
                ('attendee_name', models.CharField(max_length=50)),
                ('contact_info', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region=None)),
                ('City', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=1000)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.Doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
