# Generated by Django 2.2.7 on 2019-12-12 08:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_eyedonor'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganDonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_Donor', models.CharField(max_length=50)),
                ('attendee_name', models.CharField(max_length=50)),
                ('contact_info', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region=None)),
                ('City', models.CharField(max_length=50)),
            ],
        ),
    ]
