# Generated by Django 2.2.4 on 2019-09-21 20:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('Patient_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Patient_First_Name', models.CharField(max_length=200)),
                ('Patient_Last_Name', models.CharField(max_length=200)),
                ('Patient_Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region=None)),
                ('Patient_Picture', models.ImageField(null=True, upload_to='media')),
                ('Patient_Gender', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('Patient_DOB', models.DateField(max_length=8)),
                ('Patient_Email', models.EmailField(default='asd@rew.com', max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.City')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('Address_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Home', models.CharField(max_length=250)),
                ('Street', models.CharField(max_length=250)),
                ('Pin', models.CharField(default=0, max_length=6)),
                ('Patient_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.Profile')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.Area')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.City')),
            ],
        ),
    ]
