# Generated by Django 2.2.7 on 2019-12-01 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='Patient_ID',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='Patient_Address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.Address'),
        ),
    ]
