# Generated by Django 2.2.4 on 2019-11-02 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_auto_20191101_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Patient_Blood_Donation',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
