# Generated by Django 2.2.4 on 2019-11-04 18:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patient', '0001_initial'),
        ('Corporate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('Doctor_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Doctor_First_Name', models.CharField(max_length=200)),
                ('Doctor_Last_Name', models.CharField(max_length=200)),
                ('Doctor_DOB', models.DateField(max_length=8)),
                ('Doctor_Phone_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=13, region=None)),
                ('Doctor_Email', models.EmailField(max_length=254)),
                ('Doctor_Gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Transgender'), (4, 'Other')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('Doctor_Qualifications', models.CharField(max_length=350)),
                ('Doctor_Specialization', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('Doctor_Experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(80)])),
                ('Doctor_Picture', models.ImageField(default='default-user-image.jpg', null=True, upload_to='media')),
                ('Doctor_Activate', models.BooleanField()),
                ('Doctor_Corporate', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Corporate.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicAddress',
            fields=[
                ('Address_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Home', models.CharField(max_length=250)),
                ('Street', models.CharField(max_length=250)),
                ('Pin', models.CharField(default=0, max_length=6)),
                ('Doctor_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.Doctor')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.Area')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patient.City')),
            ],
        ),
    ]
