# Generated by Django 2.2.7 on 2019-12-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Doctor_Qualifications',
            field=models.CharField(choices=[('MBBS', 'MBBS'), ('MS', 'MS'), ('MD', 'MD'), ('DCH', 'DCH'), ('BSc', 'BSc')], max_length=350),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Doctor_Specialization',
            field=models.CharField(choices=[('Nephrologist', 'Nephrologist'), ('Psychiatrist', 'Psychiatrist'), ('Anesthesiologist', 'Anesthesiologist'), ('Podiatrist', 'Podiatrist'), ('Gynecologist', 'Gynecologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Allergist', 'Allergist'), ('Sports Medicine Specialist', 'Sports Medicine Specialist'), ('Medical Geneticist', 'Medical Geneticist'), ('Pulmonologist', 'Pulmonologist'), ('Orthopedist', 'Orthopedist'), ('Diabetologist', 'Diabetologist'), ('Oncologist', 'Oncologist'), ('Sleep Specialist', 'Sleep Specialist'), ('Colon Surgeon', 'Colon Surgeon'), ('Emergency Medicine Specialist', 'Emergency Medicine Specialist'), ('Physiatrist', 'Physiatrist'), ('Neurologist', 'Neurologist'), ('General Physician', 'General Physician'), ('Ophthalmologist', 'Ophthalmologist'), ('Neurosurgeon', 'Neurosurgeon'), ('Urologist', 'Urologist'), ('Pediatrician', 'Pediatrician'), ('Preventive Medicine Specialist', 'Preventive Medicine Specialist'), ('Cardiologist', 'Cardiologist'), ('Sleep Medicine Specialist', 'Sleep Medicine Specialist'), ('Critical Care Medicine Specialist', 'Critical Care Medicine Specialist'), ('General Surgeon', 'General Surgeon'), ('Pathologist', 'Pathologist'), ('Rheumatologist', 'Rheumatologist'), ('Palliative Medicine Specialist', 'Palliative Medicine Specialist'), ('Geriatric Medicine Specialist', 'Geriatric Medicine Specialist'), ('Osteopath', 'Osteopath'), ('Colon and Rectal Surgeon', 'Colon and Rectal Surgeon'), ('Family Physician', 'Family Physician'), ('Endocrinologist', 'Endocrinologist'), ('Plastic Surgeon', 'Plastic Surgeon'), ('Radiologist', 'Radiologist'), ('Otolaryngologist', 'Otolaryngologist'), ('Hematologist', 'Hematologist'), ('Dermatologist', 'Dermatologist'), ('Infectious Disease Specialist', 'Infectious Disease Specialist'), ('Obstetricians', 'Obstetricians')], max_length=250),
        ),
    ]
