# Generated by Django 2.2.7 on 2019-12-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Doctor_DOB',
            field=models.DateField(max_length=8, null=True),
        ),
    ]
