# Generated by Django 2.2.7 on 2019-11-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0003_appointmentbooking_docotrscheldule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docotrscheldule',
            name='interval',
            field=models.IntegerField(choices=[(10, '10 min'), (15, '15 min'), (20, '20 min'), (30, '30 min'), (60, '60 min')], default='10'),
        ),
    ]
