# Generated by Django 2.2.7 on 2019-11-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_auto_20191108_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docotrscheldule',
            name='closeTime',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='docotrscheldule',
            name='openTime',
            field=models.CharField(max_length=10),
        ),
    ]
