# Generated by Django 2.2.7 on 2019-11-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_auto_20191109_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docotrscheldule',
            name='closeTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='docotrscheldule',
            name='openTime',
            field=models.TimeField(),
        ),
    ]
