# Generated by Django 2.2.7 on 2019-11-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0009_auto_20191109_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docotrscheldule',
            name='closeTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='docotrscheldule',
            name='openTime',
            field=models.TimeField(),
        ),
    ]
