# Generated by Django 2.2.7 on 2019-11-09 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0010_auto_20191109_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docotrscheldule',
            name='closeTime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='docotrscheldule',
            name='openTime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
