# Generated by Django 2.2.7 on 2019-11-09 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0011_auto_20191109_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docotrscheldule',
            name='closeTime',
            field=models.TimeField(default=datetime.time(23, 0)),
        ),
        migrations.AlterField(
            model_name='docotrscheldule',
            name='openTime',
            field=models.TimeField(default=datetime.time(2, 0)),
        ),
    ]
