# Generated by Django 2.2.7 on 2019-11-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0016_timeslots'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appointmentBooking',
        ),
    ]
