# Generated by Django 2.2.7 on 2019-11-15 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0017_delete_appointmentbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorschedule',
            name='docUsername',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='Doctor_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Doctor.Doctor'),
            preserve_default=False,
        ),
    ]
