# Generated by Django 2.2.7 on 2019-11-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0018_auto_20191116_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorschedule',
            name='Doctor_ID',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='docUsername',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
