# Generated by Django 2.2.7 on 2019-11-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0019_auto_20191116_0253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctorSchedule',
        ),
    ]
