# Generated by Django 2.2.7 on 2019-11-15 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0021_doctorschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorschedule',
            name='docUsername',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='Doctor_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.Doctor'),
        ),
    ]
