# Generated by Django 2.2.7 on 2019-12-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0023_auto_20191201_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicaddress',
            name='ClinicAddress_ID',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
