# Generated by Django 2.2.7 on 2019-12-04 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0024_auto_20191204_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Doctor_Address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Doctor.ClinicAddress'),
        ),
    ]
